name: Build & Deploy GitHub Pages

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Install NodeJS 10
        uses: actions/setup-node@v1
        with:
          node-version: '10.x'
      - name: Install dependencies
        run: |
          npm i yarn
          yarn install
      - name: Build
        run: |
          yarn build
      - name: Deploy
        uses: crazy-max/ghaction-github-pages@v1.3.0
        with:
          repo: aiogram/aiogram.github.io
          fqdn: aiogram.dev
          build_dir: dist
          target_branch: master
          committer_email: ci@aiogram.dev
          committer_name: GitHub Actions
          commit_message: Build https://github.com/${{ github.repository }}/commit/${{ github.sha }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
